# DATA PREPARATION/DATA PREPROCESSING

### 3 Step Approach: 

**Step 1: Data Cleaning - drop, dropna. Mean, Median, mode Imputation (or) Any Value Imputation for Nan Values.**

**Step 2: Data Type Convertion(Optional)**

**Step 3: Data Transformation**

# 1. Import Necessary libraries

In [42]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# 2. Import Data

In [2]:
weather_report_2010 = pd.read_csv('data_clean.csv')
weather_report_2010

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

# 3. Data Understanding

In [3]:
weather_report_2010.shape

(158, 10)

In [4]:
weather_report_2010.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [5]:
weather_report_2010['Ozone'].mean(),weather_report_2010['Ozone'].median()

(41.583333333333336, 30.5)

In [6]:
weather_report_2010['Weather'].value_counts()

Weather
S     59
C     49
PS    47
Name: count, dtype: int64

In [7]:
weather_report_2010.head(30)

    Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0            1   41.0    190.0   7.4     67     5    1  2010    67       S
1            2   36.0    118.0   8.0     72     5    2  2010    72       C
2            3   12.0    149.0  12.6     74     5    3  2010    74      PS
3            4   18.0    313.0  11.5     62     5    4  2010    62       S
4            5    NaN      NaN  14.3     56     5    5  2010    56       S
5            6   28.0      NaN  14.9     66     5    6  2010    66       C
6            7   23.0    299.0   8.6     65     5    7  2010    65      PS
7            8   19.0     99.0  13.8     59     5    8  2010    59       C
8            9    8.0     19.0  20.1     61     5    9  2010    61      PS
9           10    NaN    194.0   8.6     69     5   10  2010    69       S
10          11    7.0      NaN   6.9      C     5   11  2010    74       C
11          12   16.0    256.0   9.7     69     5   12  2010    69      PS
12          13   11.0    290.0   9.2     66     5   13  2010    66       S
13          14   14.0    274.0  10.9     68     5   14  2010    68       S
14          15   18.0     65.0  13.2     58     5   15  2010    58       C
15          16   14.0    334.0  11.5     64     5   16  2010    64       S
16          17   34.0    307.0  12.0     66     5   17  2010    66       S
17          18    6.0     78.0  18.4     57     5   18  2010    57       C
18          19   30.0    322.0  11.5     68     5   19  2010    68      PS
19          20   11.0     44.0   9.7     62     5   20  2010    62       S
20          21    1.0      8.0   9.7     59     5   21  2010    59       S
21          22   11.0    320.0  16.6     73     5   22  2010    73       C
22          23    4.0     25.0   9.7     61     5   23  2010    61      PS
23          24   32.0     92.0  12.0     61   May   24  2010    61       C
24          25    NaN     66.0  16.6     57     5   25  2010    57      PS
25          26    NaN    266.0  14.9     58     5   26  2010    58       C
26          27    NaN      NaN   8.0     57     5   27  2010    57      PS
27          28   23.0     13.0  12.0     67     5   28  2010    67       S
28          29   45.0    252.0  14.9     81     5   29  2010    81       S
29          30  115.0    223.0   5.7     79     5   30  2010    79       C

In [8]:
weather_report_2010.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

# 4. Data Preparation

### STEP 1: Data Cleaning

## Client, Deepak agrees to drop the entire feature Ozone.

In [9]:
weather_report_2010.drop(labels = ['Unnamed: 0','Ozone'],axis=1,inplace=True)

In [10]:
weather_report_2010.isna().sum()

Solar.R    7
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [11]:
7/158

0.04430379746835443

In [12]:
weather_report_2010['Solar.R'].mean()

185.40397350993376

In [13]:
weather_report_2010['Solar.R'].median()

197.0

### =============================================TRY IT=====================================

Sir, Can't we replace the Ozone using groupby func. for each weather condition.. Below are the mean values for each weather condition.

C     46.162162

PS    42.194444

S     36.909091

### ======================================================================================

In [14]:
weather_report_2010.groupby(by = 'Weather')['Solar.R'].mean()

Weather
C     192.391304
PS    174.347826
S     193.333333
Name: Solar.R, dtype: float64

In [43]:
weather_report_2010_S = weather_report_2010[weather_report_2010['Weather'] == 'S']
weather_report_2010_S['Solar.R'].fillna(193.3,inplace=True)
weather_report_2010_S

     Solar.R  Wind  Month  Day  Year  Temp Weather
96     190.0   7.4      5    1  2010    67       S
97     313.0  11.5      5    4  2010    62       S
98     193.3  14.3      5    5  2010    56       S
99     194.0   8.6      5   10  2010    69       S
100    290.0   9.2      5   13  2010    66       S
101    274.0  10.9      5   14  2010    68       S
102    334.0  11.5      5   16  2010    64       S
103    307.0  12.0      5   17  2010    66       S
104     44.0   9.7      5   20  2010    62       S
105      8.0   9.7      5   21  2010    59       S
106     13.0  12.0      5   28  2010    67       S
107    252.0  14.9      5   29  2010    81       S
108    286.0   8.6      6    1  2010    78       S
109    273.0   6.9      6    8  2010    87       S
110    291.0  13.8      6    9  2010    90       S
111    323.0  11.5      6   10  2010    87       S
112    148.0   8.0      6   13  2010    82       S
113    332.0  13.8      6   14  2010    80       S
114    120.0  11.5      6   19  2010    73       S
115    137.0  10.3      6   20  2010    76       S
116    150.0   6.3      6   21  2010    77       S
117    250.0   6.3      6   24  2010    76       S
118     31.0  14.9      6   29  2010    77       S
119    138.0   8.0      6   30  2010    83       S
120    269.0   4.1      7    1  2010    84       S
121    101.0  10.9      7    4  2010    84       S
122    175.0   4.6      7    5  2010    83       S
123    139.0   8.6      7   11  2010    82       S
124    264.0  14.3      7   12  2010    73       S
125    175.0  14.9      7   13  2010    81       S
126    260.0   6.9      7   16  2010    81       S
127    274.0  10.3      7   17  2010    82       S
128      7.0   6.9      7   21  2010    74       S
129    258.0   9.7      7   22  2010    81       S
130    213.0   7.4      7   28  2010    88       S
131    193.3   7.4      8    5  2010    85       S
132    137.0  11.5      8   11  2010    86       S
133    192.0  11.5      8   12  2010    86       S
134    273.0  11.5      8   13  2010    82       S
135    190.0  10.3      8   20  2010    78       S
136    259.0  15.5      8   21  2010    77       S
137    215.0   8.0      8   26  2010    86       S
138    153.0   5.7      8   27  2010    88       S
139    203.0   9.7      8   28  2010    97       S
140    225.0   2.3      8   29  2010    94       S
141    237.0   6.3      8   30  2010    96       S
142     95.0   7.4      9    5  2010    87       S
143     92.0  15.5      9    6  2010    84       S
144    252.0  10.9      9    7  2010    80       S
145    259.0  15.5      9   12  2010    76       S
146    238.0   6.3      9   13  2010    77       S
147    237.0   6.9      9   16  2010    78       S
148     27.0  10.3      9   18  2010    76       S
149     14.0   9.2      9   22  2010    71       S
150    139.0  10.3      9   23  2010    81       S
151    191.0  14.3      9   28  2010    75       S
152    223.0  11.5      9   30  2010    68       S
153    145.0  13.2      9   27  2010    77       S
154    191.0  14.3      9   28  2010    75       S

In [44]:
weather_report_2010_PS = weather_report_2010[weather_report_2010['Weather'] == 'PS']
weather_report_2010_PS['Solar.R'].fillna(174.3,inplace=True)
weather_report_2010_PS

    Solar.R  Wind  Month  Day  Year  Temp Weather
49    149.0  12.6      5    3  2010    74      PS
50    299.0   8.6      5    7  2010    65      PS
51     19.0  20.1      5    9  2010    61      PS
52    256.0   9.7      5   12  2010    69      PS
53    322.0  11.5      5   19  2010    68      PS
54     25.0   9.7      5   23  2010    61      PS
55     66.0  16.6      5   25  2010    57      PS
56    174.3   8.0      5   27  2010    57      PS
57    279.0   7.4      5   31  2010    76      PS
58    242.0  16.1      6    3  2010    67      PS
59    220.0   8.6      6    5  2010    85      PS
60    127.0   9.7      6    7  2010    82      PS
61    250.0   9.2      6   12  2010    92      PS
62    191.0  14.9      6   16  2010    77      PS
63     37.0   9.2      6   18  2010    65      PS
64     91.0   4.6      6   23  2010    76      PS
65    127.0   8.0      6   26  2010    78      PS
66     98.0  11.5      6   28  2010    80      PS
67    236.0   9.2      7    3  2010    81      PS
68    267.0   6.3      7    8  2010    92      PS
69    175.0   7.4      7   10  2010    89      PS
70     48.0  14.3      7   15  2010    80      PS
71    187.0   5.1      7   19  2010    87      PS
72    294.0   8.6      7   24  2010    86      PS
73    223.0   8.0      7   25  2010    85      PS
74    253.0   7.4      7   30  2010    83      PS
75     83.0   6.9      8    1  2010    81      PS
76     77.0   7.4      8    3  2010    82      PS
77    229.0  10.3      8    8  2010    90      PS
78    222.0   8.6      8   10  2010    92      PS
79     51.0   6.3      8   17  2010    79      PS
80    244.0  10.9      8   19  2010    78      PS
81    255.0  12.6      8   23  2010    75      PS
82    238.0   3.4      8   25  2010    81      PS
83    197.0   5.1      9    2  2010    92      PS
84    189.0   4.6      9    4  2010    93      PS
85    230.0  10.9      9    9  2010    75      PS
86    236.0  14.9      9   11  2010    81      PS
87     24.0  10.9      9   14  2010    71      PS
88    112.0  11.5      9   15  2010    71      PS
89    224.0  13.8      9   17  2010    67      PS
90    201.0   8.0      9   20  2010    82      PS
91    238.0  12.6      9   21  2010    64      PS
92     20.0  16.6      9   25  2010    63      PS
93    145.0  13.2      9   27  2010    77      PS
94    131.0   8.0      9   29  2010    76      PS
95    193.0   6.9      9   26  2010    70      PS

In [17]:
import warnings
warnings.filterwarnings('ignore')

In [18]:
weather_data_2010_C = weather_report_2010[weather_report_2010['Weather'] == 'C']
weather_data_2010_C['Solar.R'].fillna(192.4,inplace=True)
weather_data_2010_C

     Solar.R  Wind Temp C Month  Day  Year  Temp Weather
1      118.0   8.0     72     5    2  2010    72       C
5      192.4  14.9     66     5    6  2010    66       C
7       99.0  13.8     59     5    8  2010    59       C
10     192.4   6.9      C     5   11  2010    74       C
14      65.0  13.2     58     5   15  2010    58       C
17      78.0  18.4     57     5   18  2010    57       C
21     320.0  16.6     73     5   22  2010    73       C
23      92.0  12.0     61   May   24  2010    61       C
25     266.0  14.9     58     5   26  2010    58       C
29     223.0   5.7     79     5   30  2010    79       C
32     287.0   9.7     74     6    2  2010    74       C
34     186.0   9.2     84     6    4  2010    84       C
36     264.0  14.3     79     6    6  2010    79       C
41     259.0  10.9     93     6   11  2010    93       C
45     322.0  11.5     79     6   15  2010    79       C
47     284.0  20.7     72     6   17  2010    72       C
52      59.0   1.7     76     6   22  2010    76       C
55     135.0   8.0     75     6   25  2010    75       C
57      47.0  10.3     73     6   27  2010    73       C
62     248.0   9.2     85     7    2  2010    85       C
66     314.0  10.9     83     7    6  2010    83       C
67     276.0   5.1     88     7    7  2010    88       C
69     272.0   5.7     92     7    9  2010    92       C
74     291.0  14.9     91     7   14  2010    91       C
78     285.0   6.3     84     7   18  2010    84       C
80     220.0  11.5     85     7   20  2010    85       C
83     295.0  11.5     82     7   23  2010    82       C
86      81.0   8.6     82     7   26  2010    82       C
89     275.0   7.4     86     7   29  2010    86       C
91     254.0   9.2     81     7   31  2010    81       C
97     192.4   4.6     87     8    6  2010    87       C
98     255.0   4.0     89     8    7  2010    89       C
100    207.0   8.0     90     8    9  2010    90       C
105    157.0   9.7     80     8   14  2010    80       C
106     64.0  11.5     79     8   15  2010    79       C
107     71.0  10.3     77     8   16  2010    77       C
109    115.0   7.4     76     8   18  2010    76       C
113     36.0  14.3     72     8   22  2010    72       C
115    212.0   9.7     79     8   24  2010    79       C
122    188.0   6.3     94     8   31  2010    94       C
123    167.0   6.9     91     9    1  2010    91       C
125    183.0   2.8     93     9    3  2010    93       C
130    220.0  10.3     78     9    8  2010    78       C
132    259.0   9.7     73     9   10  2010    73       C
141    238.0  10.3     68     9   19  2010    68       C
146     49.0  10.3     69     9   24  2010    69       C
148    193.0   6.9     70     9   26  2010    70       C
153    190.0   7.4     67     5    1  2010    67       C
157    131.0   8.0     76     9   29  2010    76       C

In [19]:
weather_report_2010 = pd.concat([weather_data_2010_C,weather_report_2010_PS,weather_report_2010_S])
weather_report_2010 = weather_report_2010.reset_index()
weather_report_2010

     index  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0        1    118.0   8.0     72     5    2  2010    72       C
1        5    192.4  14.9     66     5    6  2010    66       C
2        7     99.0  13.8     59     5    8  2010    59       C
3       10    192.4   6.9      C     5   11  2010    74       C
4       14     65.0  13.2     58     5   15  2010    58       C
..     ...      ...   ...    ...   ...  ...   ...   ...     ...
150    145    139.0  10.3     81     9   23  2010    81       S
151    150    191.0  14.3     75     9   28  2010    75       S
152    152    223.0  11.5     68     9   30  2010    68       S
153    155    145.0  13.2     77     9   27  2010    77       S
154    156    191.0  14.3     75     9   28  2010    75       S

[155 rows x 9 columns]

In [20]:
del weather_report_2010['index']

In [21]:
weather_report_2010.isna().sum()

Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [22]:
weather_report_2010.shape

(155, 8)

In [23]:
weather_report_2010.dtypes

Solar.R    float64
Wind       float64
Temp C      object
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [24]:
del weather_report_2010['Temp C']

In [25]:
weather_report_2010.head(30)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     118.0   8.0     5    2  2010    72       C
1     192.4  14.9     5    6  2010    66       C
2      99.0  13.8     5    8  2010    59       C
3     192.4   6.9     5   11  2010    74       C
4      65.0  13.2     5   15  2010    58       C
5      78.0  18.4     5   18  2010    57       C
6     320.0  16.6     5   22  2010    73       C
7      92.0  12.0   May   24  2010    61       C
8     266.0  14.9     5   26  2010    58       C
9     223.0   5.7     5   30  2010    79       C
10    287.0   9.7     6    2  2010    74       C
11    186.0   9.2     6    4  2010    84       C
12    264.0  14.3     6    6  2010    79       C
13    259.0  10.9     6   11  2010    93       C
14    322.0  11.5     6   15  2010    79       C
15    284.0  20.7     6   17  2010    72       C
16     59.0   1.7     6   22  2010    76       C
17    135.0   8.0     6   25  2010    75       C
18     47.0  10.3     6   27  2010    73       C
19    248.0   9.2     7    2  2010    85       C
20    314.0  10.9     7    6  2010    83       C
21    276.0   5.1     7    7  2010    88       C
22    272.0   5.7     7    9  2010    92       C
23    291.0  14.9     7   14  2010    91       C
24    285.0   6.3     7   18  2010    84       C
25    220.0  11.5     7   20  2010    85       C
26    295.0  11.5     7   23  2010    82       C
27     81.0   8.6     7   26  2010    82       C
28    275.0   7.4     7   29  2010    86       C
29    254.0   9.2     7   31  2010    81       C

In [26]:
weather_report_2010[weather_report_2010['Month'] == 'May'] = weather_report_2010[weather_report_2010['Month'] == 'May'].replace('May',5)

In [27]:
weather_report_2010.head(10)

   Solar.R  Wind Month  Day  Year  Temp Weather
0    118.0   8.0     5    2  2010    72       C
1    192.4  14.9     5    6  2010    66       C
2     99.0  13.8     5    8  2010    59       C
3    192.4   6.9     5   11  2010    74       C
4     65.0  13.2     5   15  2010    58       C
5     78.0  18.4     5   18  2010    57       C
6    320.0  16.6     5   22  2010    73       C
7     92.0  12.0     5   24  2010    61       C
8    266.0  14.9     5   26  2010    58       C
9    223.0   5.7     5   30  2010    79       C

In [28]:
weather_report_2010.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [29]:
weather_report_2010.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

## Step 2: Data Type Convertion

In [30]:
weather_report_2010['Month'] = weather_report_2010['Month'].astype('int')

In [31]:
weather_report_2010.dtypes

Solar.R    float64
Wind       float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [32]:
weather_report_2010.head()

   Solar.R  Wind  Month  Day  Year  Temp Weather
0    118.0   8.0      5    2  2010    72       C
1    192.4  14.9      5    6  2010    66       C
2     99.0  13.8      5    8  2010    59       C
3    192.4   6.9      5   11  2010    74       C
4     65.0  13.2      5   15  2010    58       C

## Step3: Data Transformation

### 2 Transformation Techniques: Discrete Vs Continous

**1. Discrete - Label Encoding/One Hot Encoding**

**2. Continous - MinMax Scaler/Standard Scaler/Robust Scaler**

## 1. Use Label Encoding

In [33]:
weather_report_2010_2 = weather_report_2010.copy()
weather_report_2010_2

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      118.0   8.0      5    2  2010    72       C
1      192.4  14.9      5    6  2010    66       C
2       99.0  13.8      5    8  2010    59       C
3      192.4   6.9      5   11  2010    74       C
4       65.0  13.2      5   15  2010    58       C
..       ...   ...    ...  ...   ...   ...     ...
150    139.0  10.3      9   23  2010    81       S
151    191.0  14.3      9   28  2010    75       S
152    223.0  11.5      9   30  2010    68       S
153    145.0  13.2      9   27  2010    77       S
154    191.0  14.3      9   28  2010    75       S

[155 rows x 7 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
weather_report_2010_2['Weather'] = le.fit_transform(weather_report_2010_2['Weather'])
weather_report_2010_2

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      118.0   8.0      5    2  2010    72        0
1      192.4  14.9      5    6  2010    66        0
2       99.0  13.8      5    8  2010    59        0
3      192.4   6.9      5   11  2010    74        0
4       65.0  13.2      5   15  2010    58        0
..       ...   ...    ...  ...   ...   ...      ...
150    139.0  10.3      9   23  2010    81        2
151    191.0  14.3      9   28  2010    75        2
152    223.0  11.5      9   30  2010    68        2
153    145.0  13.2      9   27  2010    77        2
154    191.0  14.3      9   28  2010    75        2

[155 rows x 7 columns]

In [35]:
weather_report_2010_2.dtypes

Solar.R    float64
Wind       float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather      int32
dtype: object

## 2. Using OneHot Encoder

It can be built by using 2 libraries:

1. sklearn - OneHotEncoder()
2. Pandas  - pd.get_dummies()

In [36]:
weather_report_2010_3 = weather_report_2010.copy()
weather_report_2010_3

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      118.0   8.0      5    2  2010    72       C
1      192.4  14.9      5    6  2010    66       C
2       99.0  13.8      5    8  2010    59       C
3      192.4   6.9      5   11  2010    74       C
4       65.0  13.2      5   15  2010    58       C
..       ...   ...    ...  ...   ...   ...     ...
150    139.0  10.3      9   23  2010    81       S
151    191.0  14.3      9   28  2010    75       S
152    223.0  11.5      9   30  2010    68       S
153    145.0  13.2      9   27  2010    77       S
154    191.0  14.3      9   28  2010    75       S

[155 rows x 7 columns]

#### 2.1 Using Pandas

In [37]:
weather_report_2010_3 = pd.get_dummies(data = weather_report_2010_3,columns=['Weather'])
weather_report_2010_3

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      118.0   8.0      5    2  2010    72       True       False      False
1      192.4  14.9      5    6  2010    66       True       False      False
2       99.0  13.8      5    8  2010    59       True       False      False
3      192.4   6.9      5   11  2010    74       True       False      False
4       65.0  13.2      5   15  2010    58       True       False      False
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
150    139.0  10.3      9   23  2010    81      False       False       True
151    191.0  14.3      9   28  2010    75      False       False       True
152    223.0  11.5      9   30  2010    68      False       False       True
153    145.0  13.2      9   27  2010    77      False       False       True
154    191.0  14.3      9   28  2010    75      False       False       True

[155 rows x 9 columns]

In [38]:
weather_report_2010_3.dtypes

Solar.R       float64
Wind          float64
Month           int32
Day             int64
Year            int64
Temp            int64
Weather_C        bool
Weather_PS       bool
Weather_S        bool
dtype: object

#### 2.2 Using Sklearn

In [39]:
weather_report_2010_4 = weather_report_2010.copy()
weather_report_2010_4

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      118.0   8.0      5    2  2010    72       C
1      192.4  14.9      5    6  2010    66       C
2       99.0  13.8      5    8  2010    59       C
3      192.4   6.9      5   11  2010    74       C
4       65.0  13.2      5   15  2010    58       C
..       ...   ...    ...  ...   ...   ...     ...
150    139.0  10.3      9   23  2010    81       S
151    191.0  14.3      9   28  2010    75       S
152    223.0  11.5      9   30  2010    68       S
153    145.0  13.2      9   27  2010    77       S
154    191.0  14.3      9   28  2010    75       S

[155 rows x 7 columns]

In [45]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit_transform(weather_report_2010_4['Weather'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

## =====================================================================

## How to choose between OHE and LE????

### Input feature:
Based on whether it is **Parametric or a Non Parametric Model**, we will choosing between LE or OHE.
* For **Parametric Models** - better to go with **OHE.**
* For **Non-Parametric Models** - always go with **Label Encoding.**

### Output feature:
Always the output feature, it must be **Label Encoder.**

## =====================================================================